/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmjava.flight;

import java.sql.Date;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import nmjava.flight.BLL.HoaDonBLL;
import nmjava.flight.BLL.VeChuyenBayBLL;
import nmjava.flight.DTO.HoaDon;
import nmjava.flight.DTO.VeChuyenBay;

/**
 *
 * @author Administrator
 */
public class SellTicketpanel extends javax.swing.JPanel {
    
    HoaDonBLL bllHD;
    VeChuyenBayBLL bllVCB;
    //ThamSoBLL bllTS;
        
    public SellTicketpanel() {
        bllHD=new HoaDonBLL();
        bllVCB=new VeChuyenBayBLL();
        //bllTS=new ThamSoBLL();
        initComponents();
        txt_HoVaTen.setText("");
        txt_CMND.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
    }
    public void setCb(ChuyenBay cb)
    {
        lbHangMayBay.setText(cb.TenHangHangKhong);
        lbNoiKhoiHanh.setText(cb.SanBayDi);
        lbGioKhoiHanh.setText(cb.ThoiGianDi);
        lbNgayKhoiHanh.setText(cb.NgayDi);
        lbMaChuyenBay.setText(cb.MaChuyenBay);
        lbNoiHaCanh.setText(cb.SanBayDen);
        lbGioHaCanh.setText(cb.ThoiGianDen);
        lbNgayHaCanh.setText(cb.NgayDen);
        lbGiaTien.setText(cb.GiaTien);
    }
    boolean CheckInput()
    {
            if (txt_HoVaTen.getText()=="")
            {
                lbNotify.setText("Bạn chưa nhập họ tên");
                return false;
            }
            if (txt_SDT.getText()=="")
            {
                lbNotify.setText("Bạn chưa nhập số điện thoại");
                return false;
            }
            if (txt_CMND.getText()=="")
            {
                lbNotify.setText("Bạn chưa nhập CMND");
                return false;
            }
            if (txt_Email.getText()=="")
            {
                lbNotify.setText("Bạn chưa nhập Email");
                return false;
            }
            return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CMND = new javax.swing.JTextField();
        lbGiaTien = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbHangMayBay = new javax.swing.JLabel();
        txt_HoVaTen = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableThongTinVe = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        lbNotify = new javax.swing.JLabel();
        lbHoVaTen5 = new javax.swing.JLabel();
        lbCMND5 = new javax.swing.JLabel();
        lbEmail5 = new javax.swing.JLabel();
        lbSDT5 = new javax.swing.JLabel();
        btn_DatVe5 = new javax.swing.JButton();
        lbNoiKhoiHanh = new javax.swing.JLabel();
        lbGioHaCanh = new javax.swing.JLabel();
        lbGioKhoiHanh = new javax.swing.JLabel();
        lbNgayKhoiHanh = new javax.swing.JLabel();
        lbNgayHaCanh = new javax.swing.JLabel();
        lbMaChuyenBay = new javax.swing.JLabel();
        lbNoiHaCanh = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbTongHoaDon = new javax.swing.JLabel();
        btn_XuatVe = new javax.swing.JButton();
        lbTongTien = new javax.swing.JLabel();

        txt_CMND.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_CMND.setForeground(new java.awt.Color(51, 51, 51));
        txt_CMND.setToolTipText("Họ và tên");
        txt_CMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CMNDActionPerformed(evt);
            }
        });

        lbGiaTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbGiaTien.setForeground(new java.awt.Color(255, 153, 0));
        lbGiaTien.setText("Giá tiền");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 153, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("THÔNG TIN ĐẶT VÉ");
        jLabel19.setOpaque(true);

        lbHangMayBay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHangMayBay.setText("Hãng máy bay");

        txt_HoVaTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_HoVaTen.setForeground(new java.awt.Color(51, 51, 51));
        txt_HoVaTen.setToolTipText("CMND");

        txt_SDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_SDT.setForeground(new java.awt.Color(51, 51, 51));
        txt_SDT.setToolTipText("Số điện thoại");

        txt_Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_Email.setForeground(new java.awt.Color(51, 51, 51));
        txt_Email.setToolTipText("Email");

        tableThongTinVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chuyến bay", "Giá tiền", "Họ và tên", "CMND", "Số điện thoại", "Email"
            }
        ));
        jScrollPane7.setViewportView(tableThongTinVe);

        jLabel20.setBackground(new java.awt.Color(111, 131, 149));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Thông tin vé");
        jLabel20.setOpaque(true);

        lbNotify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNotify.setForeground(new java.awt.Color(0, 204, 51));
        lbNotify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotify.setText("Thông báo");

        lbHoVaTen5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHoVaTen5.setText("Họ và tên:");

        lbCMND5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCMND5.setText("CMND:");

        lbEmail5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail5.setText("Email:");

        lbSDT5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSDT5.setText("Số điện thoại:");

        btn_DatVe5.setBackground(new java.awt.Color(102, 153, 255));
        btn_DatVe5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_DatVe5.setForeground(new java.awt.Color(255, 255, 255));
        btn_DatVe5.setText("Đặt vé");
        btn_DatVe5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DatVe5ActionPerformed(evt);
            }
        });

        lbNoiKhoiHanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNoiKhoiHanh.setText("Nơi khởi hành");

        lbGioHaCanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbGioHaCanh.setText("GIỜ HẠ CÁNH");

        lbGioKhoiHanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbGioKhoiHanh.setText("GIỜ KHỞI HÀNH");

        lbNgayKhoiHanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNgayKhoiHanh.setText("Ngày khởi hành");

        lbNgayHaCanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNgayHaCanh.setText("Ngày hạ cánh");

        lbMaChuyenBay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaChuyenBay.setForeground(new java.awt.Color(0, 204, 51));
        lbMaChuyenBay.setText("Mã chuyến bay");

        lbNoiHaCanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNoiHaCanh.setText("Nơi hạ cánh");

        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Nam3_Ki1\\Java\\Flight\\resource\\flightIcon.PNG")); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon("D:\\Nam3_Ki1\\Java\\Flight\\resource\\flightarrow.PNG")); // NOI18N

        lbTongHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTongHoaDon.setForeground(new java.awt.Color(255, 153, 0));
        lbTongHoaDon.setText("Tổng hóa đơn:");

        btn_XuatVe.setBackground(new java.awt.Color(102, 153, 255));
        btn_XuatVe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_XuatVe.setForeground(new java.awt.Color(255, 255, 255));
        btn_XuatVe.setText("Xuất Vé");
        btn_XuatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XuatVeActionPerformed(evt);
            }
        });

        lbTongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTongTien.setForeground(new java.awt.Color(255, 153, 0));
        lbTongTien.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMaChuyenBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51)
                .addComponent(lbNoiHaCanh)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(lbNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbHoVaTen5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbCMND5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(lbHangMayBay)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(lbNgayKhoiHanh))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lbGioKhoiHanh)))))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNoiKhoiHanh)
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSDT5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_SDT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(txt_Email))
                                        .addGap(24, 24, 24)
                                        .addComponent(btn_DatVe5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(lbNgayHaCanh))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addComponent(lbGioHaCanh)
                                .addGap(45, 45, 45)
                                .addComponent(lbGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTongHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_XuatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNoiKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNoiHaCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMaChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbGioKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbHangMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbGioHaCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNgayHaCanh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSDT5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHoVaTen5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Email)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCMND5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_DatVe5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbNotify, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XuatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        txt_CMND.getAccessibleContext().setAccessibleDescription("CMND");
        txt_HoVaTen.getAccessibleContext().setAccessibleDescription("Họ và tên");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DatVe5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DatVe5ActionPerformed
        if(CheckInput())
        {
            DefaultTableModel model = (DefaultTableModel) tableThongTinVe.getModel();
            Object[] row = {lbMaChuyenBay.getText(),lbGiaTien.getText(),txt_HoVaTen.getText(),txt_CMND.getText(),txt_SDT.getText(),txt_Email.getText()};
            model.addRow(row);
            String giatien="";
            String tmp=lbGiaTien.getText();
            for (char ch: tmp.toCharArray()) 
            {
                if(ch>='0'&&ch<='9')
                    giatien+=ch;
            }
            lbTongTien.setText(String.valueOf(Integer.parseInt(lbTongTien.getText())+Integer.parseInt(giatien)));
            //System.out.println(Integer.parseInt(lbTongTien.getText())+Integer.parseInt(giatien));
            txt_HoVaTen.setText("");
            txt_CMND.setText("");
            txt_SDT.setText("");
            txt_Email.setText(""); 
            
        }
        
    }//GEN-LAST:event_btn_DatVe5ActionPerformed

    private void txt_CMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CMNDActionPerformed

    private void btn_XuatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XuatVeActionPerformed
        if(tableThongTinVe.getRowCount()==0)
        {
            lbNotify.setText("Bạn chưa nhập Email");
            
        }
        else
        {
            HoaDon HD = new HoaDon();
            HD.setMaHoaDon(bllHD.getMaHoaDon());
            System.out.println(HD.MaHoaDon);
            HD.TienLai=tableThongTinVe.getRowCount()*0;
            HD.SoVe=tableThongTinVe.getRowCount();
            HD.TongTien=Double.parseDouble(lbTongTien.getText());
            HD.ThoiGianTao=Date.valueOf(Calendar.getInstance().toString());
            bllHD.InsertHoaDon(HD);
            for(int i=0;i<tableThongTinVe.getRowCount();i++)
            {
                 VeChuyenBay VCB = new VeChuyenBay();
                 VCB.MaChuyenBay=tableThongTinVe.getValueAt(i, 0).toString();
                 VCB.GiaVe=Integer.parseInt(tableThongTinVe.getValueAt(i, 1).toString());
                 VCB.HoTen=tableThongTinVe.getValueAt(i, 2).toString();
                 VCB.CMND=tableThongTinVe.getValueAt(i, 3).toString();
                 VCB.SDT=tableThongTinVe.getValueAt(i, 4).toString();
                 VCB.Email=tableThongTinVe.getValueAt(i, 5).toString();
                 VCB.MaHoaDon = HD.MaHoaDon;
                 VCB.TrangThai="Đã thanh toán";
                 bllVCB.InsertVeChuyenBay(VCB);
            }
            lbNotify.setText("Xuất vé thành công");
            DefaultTableModel model = (DefaultTableModel) tableThongTinVe.getModel();
            model.setRowCount(0);
        }
    }//GEN-LAST:event_btn_XuatVeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DatVe5;
    private javax.swing.JButton btn_XuatVe;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbCMND5;
    private javax.swing.JLabel lbEmail5;
    private javax.swing.JLabel lbGiaTien;
    private javax.swing.JLabel lbGioHaCanh;
    private javax.swing.JLabel lbGioKhoiHanh;
    private javax.swing.JLabel lbHangMayBay;
    private javax.swing.JLabel lbHoVaTen5;
    private javax.swing.JLabel lbMaChuyenBay;
    private javax.swing.JLabel lbNgayHaCanh;
    private javax.swing.JLabel lbNgayKhoiHanh;
    private javax.swing.JLabel lbNoiHaCanh;
    private javax.swing.JLabel lbNoiKhoiHanh;
    private javax.swing.JLabel lbNotify;
    private javax.swing.JLabel lbSDT5;
    private javax.swing.JLabel lbTongHoaDon;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JTable tableThongTinVe;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoVaTen;
    private javax.swing.JTextField txt_SDT;
    // End of variables declaration//GEN-END:variables
}
